# Generated by Django 5.2.6 on 2025-09-09 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('sepatu bola', 'Sepatu Bola'), ('kaos kaki', 'Kaos Kaki'), ('jersey', 'Jersey'), ('tas bola', 'Tas Bola'), ('bola', 'Bola')], default='ball', max_length=20)),
                ('thumbnail', models.URLField(blank=True, null=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('stock', models.IntegerField(default=0)),
            ],
        ),
    ]
